name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: kaidenzz77

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: pacman-output
